### ISSUE TITLE
BibEdit: Button in sidebar for autosuggest

### ISSUE THREAD

**Issue by audub** [tind/invenio-fork#17]
From Alex via support

Can we make a special button for called "Autosuggest input"? So it is more intuitive in case you don't know the shortcut. Mockup:

![screen shot 2015-02-18 at 10 57 39](https://cloud.githubusercontent.com/assets/2854307/6306364/2c5d1372-b933-11e4-959d-8eb26caac248.png)

**Comment by audub** [comment]
The button is abandoned due to implementation complications. @PXke has created a tooltip telling the user about the command when he enters a field with autocompletion abilities.

**Comment by PXke** [comment]
I confirm I tried again. It is possible but it will take a lot of time to study a way to do it or rewrite a big chunk. 

I close the issue at the moment.

**Comment by nietzold** [comment]
You have implemented a autosuggest notification instead, a popup box so to
say? I did not find it at hr-mig2.

best regards
Alexander Nietzold
tlf: +47 926 42 726

**Comment by PXke** [comment]
Yes it works only if you hover it long enough I will change that.

**Comment by blixhavn** [comment]
This issue was moved to tind/invenio#1
