### ISSUE TITLE
BibEdit: Comments to current work

### ISSUE THREAD

**Issue by Kennethhole** [tind/invenio-fork#32]
Epic!
I like what I see. Did not find any erros. I found room for some small improvements, but I think it is just configuration settings.

1. Add only main field (a), and not other subfields (such as 0). Should be default.
![screenshot 2015-04-08 10 29 55](https://cloud.githubusercontent.com/assets/6758333/7041921/e9210a4e-dddd-11e4-97e2-de82dbf88ae8.png)

2. 61024 field need to be added to the list of corporate in authority config file

**Comment by nietzold** [comment]
Is this a task? Or a RFC?

**Comment by Kennethhole** [comment]
This is a comment in reviewing the modifications Guillaume have done in bibedit.

**Comment by blixhavn** [comment]
This issue was moved to tind/invenio#4
