### ISSUE TITLE
BibEdit: Font size

### ISSUE THREAD

**Issue by audub** [tind/invenio-fork#33]
From Alex via support: 

When selecting a field to edit, can we keep the same font/font size as is the case when just 'displayed'? That way, we avoid the annoying "jumping" every time you click on a field.

![unnamed](https://cloud.githubusercontent.com/assets/2854307/7048688/c7bfd10a-de14-11e4-84b9-b8fb636e6db2.png)

**Comment by blixhavn** [comment]
This issue was moved to tind/invenio#5
